[2024-01-08T06:35:58.069+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_dwh.wait_etl_to_datalake_table_source_a scheduled__2024-01-07T02:00:00+00:00 [queued]>
[2024-01-08T06:35:58.086+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_dwh.wait_etl_to_datalake_table_source_a scheduled__2024-01-07T02:00:00+00:00 [queued]>
[2024-01-08T06:35:58.087+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 4
[2024-01-08T06:35:58.110+0000] {taskinstance.py:2192} INFO - Executing <Task(ExternalTaskSensor): wait_etl_to_datalake_table_source_a> on 2024-01-07 02:00:00+00:00
[2024-01-08T06:35:58.121+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-01-08T06:35:58.130+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_dwh', 'wait_etl_to_datalake_table_source_a', 'scheduled__2024-01-07T02:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_dwh.py', '--cfg-path', '/tmp/tmpn3ik9pkw']
[2024-01-08T06:35:58.133+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask wait_etl_to_datalake_table_source_a
[2024-01-08T06:35:58.210+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_dwh.wait_etl_to_datalake_table_source_a scheduled__2024-01-07T02:00:00+00:00 [running]> on host 6d1c1d696e23
[2024-01-08T06:35:58.341+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_dwh' AIRFLOW_CTX_TASK_ID='wait_etl_to_datalake_table_source_a' AIRFLOW_CTX_EXECUTION_DATE='2024-01-07T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-07T02:00:00+00:00'
[2024-01-08T06:35:58.346+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 263, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 245, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 240, in poke
    dttm_filter = self._get_dttm_filter(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 227, in _get_dttm_filter
    dttm = context["logical_date"] - self.execution_delta
TypeError: unsupported operand type(s) for -: 'DateTime' and 'str'
[2024-01-08T06:35:58.357+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_to_dwh, task_id=wait_etl_to_datalake_table_source_a, execution_date=20240107T020000, start_date=20240108T063558, end_date=20240108T063558
[2024-01-08T06:35:58.373+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task wait_etl_to_datalake_table_source_a (unsupported operand type(s) for -: 'DateTime' and 'str'; 96)
[2024-01-08T06:35:58.388+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T06:35:58.419+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-08T07:48:01.927+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_dwh.wait_etl_to_datalake_table_source_a scheduled__2024-01-07T02:00:00+00:00 [queued]>
[2024-01-08T07:48:01.951+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_dwh.wait_etl_to_datalake_table_source_a scheduled__2024-01-07T02:00:00+00:00 [queued]>
[2024-01-08T07:48:01.952+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 4
[2024-01-08T07:48:01.981+0000] {taskinstance.py:2192} INFO - Executing <Task(ExternalTaskSensor): wait_etl_to_datalake_table_source_a> on 2024-01-07 02:00:00+00:00
[2024-01-08T07:48:01.996+0000] {standard_task_runner.py:60} INFO - Started process 151 to run task
[2024-01-08T07:48:02.003+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_dwh', 'wait_etl_to_datalake_table_source_a', 'scheduled__2024-01-07T02:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_dwh.py', '--cfg-path', '/tmp/tmpprg4gsln']
[2024-01-08T07:48:02.006+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask wait_etl_to_datalake_table_source_a
[2024-01-08T07:48:02.148+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_dwh.wait_etl_to_datalake_table_source_a scheduled__2024-01-07T02:00:00+00:00 [running]> on host 6d1c1d696e23
[2024-01-08T07:48:02.505+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_dwh' AIRFLOW_CTX_TASK_ID='wait_etl_to_datalake_table_source_a' AIRFLOW_CTX_EXECUTION_DATE='2024-01-07T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-07T02:00:00+00:00'
[2024-01-08T07:48:02.520+0000] {external_task.py:244} INFO - Poking for tasks ['table_source_a'] in dag etl_to_datalake on 2024-01-07T00:00:00+00:00 ... 
[2024-01-08T07:48:02.551+0000] {base.py:293} INFO - Success criteria met. Exiting.
[2024-01-08T07:48:02.583+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_dwh, task_id=wait_etl_to_datalake_table_source_a, execution_date=20240107T020000, start_date=20240108T074801, end_date=20240108T074802
[2024-01-08T07:48:02.675+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-08T07:48:02.731+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
