[2024-01-08T05:03:17.479+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-08T05:03:17.493+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-08T05:03:17.494+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-08T05:03:17.514+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): table_source_a> on 2024-01-07 00:00:00+00:00
[2024-01-08T05:03:17.526+0000] {standard_task_runner.py:60} INFO - Started process 221 to run task
[2024-01-08T05:03:17.532+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_datalake', 'table_source_a', 'scheduled__2024-01-07T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_datalake.py', '--cfg-path', '/tmp/tmprfz_k9pk']
[2024-01-08T05:03:17.534+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask table_source_a
[2024-01-08T05:03:17.620+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [running]> on host 6d1c1d696e23
[2024-01-08T05:03:17.717+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_datalake' AIRFLOW_CTX_TASK_ID='table_source_a' AIRFLOW_CTX_EXECUTION_DATE='2024-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-07T00:00:00+00:00'
[2024-01-08T05:03:17.735+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-08T05:03:17.803+0000] {logging_mixin.py:188} INFO - successfully created BQ client
[2024-01-08T05:03:17.804+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_to_datalake.py", line 60, in load_query_result_to_bq
    raise e
  File "/opt/airflow/dags/etl_to_datalake.py", line 56, in load_query_result_to_bq
    query_job = bq_client.query(dict_config["query"], job_config=job_config)
KeyError: 'query'
[2024-01-08T05:03:17.815+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_to_datalake, task_id=table_source_a, execution_date=20240107T000000, start_date=20240108T050317, end_date=20240108T050317
[2024-01-08T05:03:17.828+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 28 for task table_source_a ('query'; 221)
[2024-01-08T05:03:17.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-08T05:03:17.890+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-08T07:21:02.035+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-08T07:21:02.050+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-08T07:21:02.051+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-08T07:21:02.076+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): table_source_a> on 2024-01-07 00:00:00+00:00
[2024-01-08T07:21:02.084+0000] {standard_task_runner.py:60} INFO - Started process 146 to run task
[2024-01-08T07:21:02.092+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_datalake', 'table_source_a', 'scheduled__2024-01-07T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_datalake.py', '--cfg-path', '/tmp/tmpt7vbqxw8']
[2024-01-08T07:21:02.094+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask table_source_a
[2024-01-08T07:21:02.180+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [running]> on host 6d1c1d696e23
[2024-01-08T07:21:02.306+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_datalake' AIRFLOW_CTX_TASK_ID='table_source_a' AIRFLOW_CTX_EXECUTION_DATE='2024-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-07T00:00:00+00:00'
[2024-01-08T07:21:02.350+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-08T07:21:02.424+0000] {logging_mixin.py:188} INFO - successfully created BQ client
[2024-01-08T07:21:05.471+0000] {logging_mixin.py:188} INFO - successfully load data to alpine-life-350508.project_x_datalake.table_source_a
[2024-01-08T07:21:05.471+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-08T07:21:05.486+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_datalake, task_id=table_source_a, execution_date=20240107T000000, start_date=20240108T072102, end_date=20240108T072105
[2024-01-08T07:21:05.519+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-08T07:21:05.550+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-08T07:29:47.759+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-08T07:29:47.786+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-08T07:29:47.787+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-08T07:29:47.817+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): table_source_a> on 2024-01-07 00:00:00+00:00
[2024-01-08T07:29:47.838+0000] {standard_task_runner.py:60} INFO - Started process 336 to run task
[2024-01-08T07:29:47.859+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_datalake', 'table_source_a', 'scheduled__2024-01-07T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_datalake.py', '--cfg-path', '/tmp/tmpy0rdl5t8']
[2024-01-08T07:29:47.867+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask table_source_a
[2024-01-08T07:29:48.035+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_datalake.table_source_a scheduled__2024-01-07T00:00:00+00:00 [running]> on host 6d1c1d696e23
[2024-01-08T07:29:48.317+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_datalake' AIRFLOW_CTX_TASK_ID='table_source_a' AIRFLOW_CTX_EXECUTION_DATE='2024-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-07T00:00:00+00:00'
[2024-01-08T07:29:48.394+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-08T07:29:48.572+0000] {logging_mixin.py:188} INFO - successfully created BQ client
[2024-01-08T07:29:55.970+0000] {logging_mixin.py:188} INFO - successfully load data to alpine-life-350508.project_x_datalake.table_source_a
[2024-01-08T07:29:55.971+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-08T07:29:55.983+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_datalake, task_id=table_source_a, execution_date=20240107T000000, start_date=20240108T072947, end_date=20240108T072955
[2024-01-08T07:29:56.015+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-08T07:29:56.044+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
