[2024-01-08T08:30:17.037+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [queued]>
[2024-01-08T08:30:17.130+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [queued]>
[2024-01-08T08:30:17.131+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-08T08:30:17.258+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fact_c> on 2024-01-06 02:00:00+00:00
[2024-01-08T08:30:17.326+0000] {standard_task_runner.py:60} INFO - Started process 173 to run task
[2024-01-08T08:30:17.380+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_dwh', 'fact_c', 'scheduled__2024-01-06T02:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_dwh.py', '--cfg-path', '/tmp/tmp6svjojiw']
[2024-01-08T08:30:17.382+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask fact_c
[2024-01-08T08:30:17.760+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [running]> on host 10dcfd4879e8
[2024-01-08T08:30:18.256+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_dwh' AIRFLOW_CTX_TASK_ID='fact_c' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T02:00:00+00:00'
[2024-01-08T08:30:18.320+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-08T08:30:18.563+0000] {logging_mixin.py:188} INFO - successfully created BQ client
[2024-01-08T08:30:21.801+0000] {logging_mixin.py:188} INFO - successfully load data to alpine-life-350508.project_x_dwh.fact_c
[2024-01-08T08:30:21.801+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-08T08:30:21.812+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_dwh, task_id=fact_c, execution_date=20240106T020000, start_date=20240108T083017, end_date=20240108T083021
[2024-01-08T08:30:21.852+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-08T08:30:21.891+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-13T12:02:52.887+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [queued]>
[2024-01-13T12:02:52.942+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [queued]>
[2024-01-13T12:02:52.942+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-13T12:02:53.004+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fact_c> on 2024-01-06 02:00:00+00:00
[2024-01-13T12:02:53.032+0000] {standard_task_runner.py:60} INFO - Started process 167 to run task
[2024-01-13T12:02:53.048+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_dwh', 'fact_c', 'scheduled__2024-01-06T02:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_dwh.py', '--cfg-path', '/tmp/tmpnsgy4ej4']
[2024-01-13T12:02:53.054+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask fact_c
[2024-01-13T12:02:53.162+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [running]> on host cc6de2d520c9
[2024-01-13T12:02:53.280+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_dwh' AIRFLOW_CTX_TASK_ID='fact_c' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T02:00:00+00:00'
[2024-01-13T12:02:53.306+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_to_dwh.py", line 59, in load_query_result_to_bq
    raise e
  File "/opt/airflow/dags/etl_to_dwh.py", line 45, in load_query_result_to_bq
    bq_client = init_bq_client()
  File "/opt/airflow/dags/etl_to_dwh.py", line 35, in init_bq_client
    raise e
  File "/opt/airflow/dags/etl_to_dwh.py", line 25, in init_bq_client
    conn = Connection.get_connection_from_secrets(conn_id='dwh-creds')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `dwh-creds` isn't defined
[2024-01-13T12:02:53.311+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_to_dwh, task_id=fact_c, execution_date=20240106T020000, start_date=20240113T120252, end_date=20240113T120253
[2024-01-13T12:02:53.326+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task fact_c (The conn_id `dwh-creds` isn't defined; 167)
[2024-01-13T12:02:53.345+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-13T12:02:53.376+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-13T12:22:35.460+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [queued]>
[2024-01-13T12:22:35.549+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [queued]>
[2024-01-13T12:22:35.557+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-13T12:22:35.737+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fact_c> on 2024-01-06 02:00:00+00:00
[2024-01-13T12:22:35.817+0000] {standard_task_runner.py:60} INFO - Started process 464 to run task
[2024-01-13T12:22:35.897+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_dwh', 'fact_c', 'scheduled__2024-01-06T02:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_dwh.py', '--cfg-path', '/tmp/tmpytx4gpmc']
[2024-01-13T12:22:35.928+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask fact_c
[2024-01-13T12:22:36.433+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_dwh.fact_c scheduled__2024-01-06T02:00:00+00:00 [running]> on host cc6de2d520c9
[2024-01-13T12:22:37.122+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_dwh' AIRFLOW_CTX_TASK_ID='fact_c' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T02:00:00+00:00'
[2024-01-13T12:22:37.191+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-13T12:22:37.854+0000] {logging_mixin.py:188} INFO - successfully created BQ client
[2024-01-13T12:22:42.497+0000] {logging_mixin.py:188} INFO - successfully load data to alpine-life-350508.project_x_dwh.fact_c
[2024-01-13T12:22:42.499+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-13T12:22:42.518+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_dwh, task_id=fact_c, execution_date=20240106T020000, start_date=20240113T122235, end_date=20240113T122242
[2024-01-13T12:22:42.621+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-13T12:22:42.683+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
